project:
  type: website
  output-dir: docs

website:
  title: "Causal Inference Resources"
  site-url: "https://kevinli03.github.io/pspe/"
  search: false
  navbar:
      pinned: true
      title: false
      background: info
      left:
        - text: "Home"
          href: index.qmd
        - text: "Difference-in-Differences"
          href: did/did.qmd
        - text: "Regression Discontinuity"
          href: rdd/rdd.qmd
        - text: "Selection on Observables"
          href: soo/soo.qmd
        - text: "Regression Models"
          href: reg/reg.qmd
        - text: "Latent Variable Models"
          href: latent/latent.qmd

  sidebar:
    - title: "Causal Inference Basics"
      style: floating
      logo: lse2.png
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Homepage"
          href: index.qmd
        - text: "Additional Resources"
          href: resources.qmd
        - text: "---"
        - text: "Basics of Causality"
          href: frameworks.qmd
        - text: "Issue of Selection Bias"
          href: correlation.qmd
        - text: "Magic of Randomisation"
          href: randomisation.qmd
        - text: "Estimators and Inference"
        - text: "Instrumental Variables"

    - title: "Difference-in-Differences"
      style: floating
      logo: lse2.png
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Difference-in-Differences"
          href: did/did.qmd
        - text: "Two-way Fixed Effects"
          href: did/twfe.qmd
        - text: "Dynamic Treatment Effects"
          href: did/dynamic.qmd
        - text: "---"
        - text: "Staggered DiD Design"
          href: did/staggered.qmd
        - text: "Issues with TWFE"
          href: did/twfestaggered.qmd
        - text: "Gardner (2021) 2-stage DiD"
          href: did/did2s.qmd
        - text: "Liu et al (2024) IFEct"
          href: did/ifect.qmd
        - text: "Wooldridge (2021) ETWFE"
          href: did/etwfe.qmd
        - text: "Sun and Abraham (2021)"
          href: did/sunab.qmd
        - text: "Callaway and Sant'Anna (2021)"
          href: did/cs.qmd
        - text: "Chaisemartin and Haultfoeuille (2024)"
    
    - title: "Regression Discontinuity"
      style: floating
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Regression Discontinuity"
          href: rdd/rdd.qmd
        - text: "---"
        - text: "Linear Parametric Model"
        - text: "Polynomial Parametric Model"
        - text: "Non-Parametric Model"
        - text: "Bandwidth Selection"
        - text: "Tests for Sorting"
        - text: "---"
        - text: "Fuzzy Discontinuity"
        - text: "Regression Kink Design"
        - text: "Panel and Spatial Data"

    - title: "Selection on Observables"
      style: floating
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Selection on Observables"
          href: soo/soo.qmd
        - text: "Choosing an Estimator"
          href: soo/soochoose.qmd
        - text: "---"
        - text: "Linear Regression Estimator"
          href: soo/regress.qmd
        - text: "Fully Interacted Estimator"
          href: soo/interact.qmd
        - text: "Causal Forests"
        - text: "---"
        - text: "Distance Matching"
          href: soo/distance.qmd
        - text: "Propensity Score Matching"
          href: soo/pscore.qmd
        - text: "Genetic Matching"
          href: soo/genetic.qmd
        - text: "---"
        - text: "Inverse Probability Weighting"
          href: soo/ipw.qmd
        - text: "Doubly Robust Estimation"
    
    - title: "Regression"
      style: floating
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Regression Models"
          href: reg/reg.qmd
        - text: "---"
        - text: "Multiple Linear Regression"
        - text: "Binomial Logistic Regression"
        - text: "Ordinal Logistic Regression"
        - text: "Multinomial Logistic Regression"
        - text: "Negative Binomial Regression"
        - text: "Poisson Regression"
        - text: "---"
        - text: "Interaction Effects"
        - text: "Variable Transformations"
        - text: "---"
        - text: "Random Forest"
        
    - title: "Latent Models"
      style: floating
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Latent Variable Models"
          href: latent/latent.qmd
        - text: "---"
        - text: "Factor Analysis Models"
          href: latent/factor.qmd
        - text: "Reliability and Factor Scores"
          href: latent/scores.qmd
        - text: "Multiple Latent Factors"
          href: latent/multiplefac.qmd
        - text: "Identification and Rotation"
          href: latent/identify.qmd
        - text: "Confirmatory Analysis"
          href: latent/confirmatory.qmd
        - text: "Item Response Theory"
          href: latent/irt.qmd
        - text: "Latent Class Models"
          href: latent/class.qmd
        - text: "---"
        - text: "Structural Equation Models"
          href: latent/sem.qmd
        - text: "Lagged Response Models"
          href: latent/longitudinal.qmd
        - text: "Multiple Group Models"
          href: latent/group.qmd
        - text: "---"
        - text: "Principle Components Analysis"
          href: latent/pca.qmd
        - text: "Cluster Analysis"
          href: latent/cluster.qmd
  
format:
  html:
    theme: cosmo
    number-sections: false
    fontsize: 12.5pt
    mainfont: helvetica
    fontcolor: "#3b4b57"
    linkcolor: "#0969da"
    css: styles.css
    toc: true
    toc-depth: 0
    tbl-cap-location: bottom
    reference-location: section
    grid:
      sidebar-width: 270px
      body-width: 720px
      margin-width: 50px
      gutter-width: 1.5em
    html-math-method: mathjax
    crossref:
      eq-prefix: eq.
      def-prefix: definition
      thm-prefix: theorem
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
    include-after-body:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

editor: visual

