project:
  type: website
  output-dir: docs

website:
  title: "Causal Inference Resources"
  site-url: "https://kevinli03.github.io/pspe/"
  search: false
  navbar:
      pinned: true
      title: false
      background: info
      left:
        - text: "Home"
          href: index.qmd
        - text: "Difference-in-Differences"
          href: did/did.qmd
        - text: "Regression Discontinuity"
          href: rdd/rdd.qmd
        - text: "Selection on Observables"
          href: soo/soo.qmd
        - text: "Regression Models"
          href: reg/reg.qmd
        - text: "Latent Variable Models"
          href: latent/latent.qmd

  sidebar:
    - title: "Causal Inference Basics"
      style: floating
      logo: lse2.png
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Homepage"
          href: index.qmd
        - text: "Additional Resources"
          href: resources.qmd
        - text: "---"
        - text: "Basics of Causality"
          href: frameworks.qmd
        - text: "Issue of Selection Bias"
          href: correlation.qmd
        - text: "Magic of Randomisation"
          href: randomisation.qmd

    - title: "Difference-in-Differences"
      style: floating
      logo: lse2.png
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Difference-in-Differences"
          href: did/did.qmd
        - text: "Two-way Fixed Effects"
          href: did/twfe.qmd
        - text: "Dynamic Treatment Effects"
          href: did/dynamic.qmd
        - text: "---"
        - text: "Staggered DiD and TWFE"
          href: did/staggered.qmd
        - text: "Sun and Abraham (2021)"
          href: did/sunab.qmd
        - text: "Callaway and Sant'Anna (2021)"
          href: did/cs.qmd
        - text: "2-stage Difference-in-Differences"
          href: did/did2s.qmd
        - text: "IFE Counterfactual Estimator"
          href: did/ifect.qmd
        - text: "Extended Two-way Fixed Effects"
          href: did/etwfe.qmd
        - text: "Chaisemartin and Haultfoeuille (2024)"
    
    - title: "Regression Discontinuity"
      style: floating
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Regression Discontinuity"
          href: rdd/rdd.qmd
        - text: "---"
        - text: "Linear Parametric Model"
        - text: "Polynomial Parametric Model"
        - text: "Non-Parametric Model"
        - text: "Bandwidth Selection"
        - text: "Tests for Sorting"
        - text: "---"
        - text: "Fuzzy Discontinuity"
        - text: "Regression Kink Design"
        - text: "Panel and Spatial Data"

    - title: "Selection on Observables"
      style: floating
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Selection on Observables"
          href: soo/soo.qmd
        - text: "Fully Interacted Estimator"
          href: soo/interact.qmd
        - text: "Distance Matching"
          href: soo/distance.qmd
        - text: "Propensity Score Matching"
          href: soo/pscore.qmd
        - text: "Genetic Matching"
          href: soo/genetic.qmd
        - text: "Inverse Probability Weighting"
          href: soo/ipw.qmd
        - text: "---"
        - text: "Causal Forests"
        - text: "Doubly Robust Estimation"
    
    - title: "Regression"
      style: floating
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Multiple Linear Regression"
          href: reg/reg.qmd
        - text: "Binomial Logistic Regression"
        - text: "Ordinal Logistic Regression"
        - text: "Multinomial Logistic Regression"
        - text: "Negative Binomial Regression"
        - text: "Poisson Regression"
        - text: "---"
        - text: "Instrumental Variables Regression"
        - text: "Grouped and Panel Data"
        - text: "Models for Time Series"
        - text: "Polynomial Regression"
        - text: "Regression Trees"
        
    - title: "Latent Models"
      style: floating
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Latent Variable Models"
          href: latent/latent.qmd
        - text: "Factor Analysis Models"
          href: latent/factor.qmd
        - text: "Item Response Theory"
          href: latent/irt.qmd
        - text: "Latent Class Models"
          href: latent/class.qmd
        - text: "Structural Equation Models"
          href: latent/sem.qmd
        - text: "---"
        - text: "Principle Components Analysis"
          href: latent/pca.qmd
        - text: "Cluster Analysis"
          href: latent/cluster.qmd

format:
  html:
    theme: cosmo
    number-sections: false
    fontsize: 12pt
    mainfont: helvetica
    fontcolor: "#3b4b57"
    linkcolor: "#0969da"
    css: styles.css
    toc: true
    toc-depth: 0
    tbl-cap-location: bottom
    reference-location: section
    df-print: kable
    grid:
      sidebar-width: 270px
      body-width: 720px
      margin-width: 50px
      gutter-width: 1.5em
    html-math-method: mathjax
    crossref:
      eq-prefix: eq.
      def-prefix: definition
      thm-prefix: theorem
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
    include-after-body:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

editor: visual

