project:
  type: website
  output-dir: docs

website:
  title: "Causal Inference Resources"
  search: false
  navbar:
      pinned: true
      title: false
      background: info
      left:
        - text: "Home"
          href: index.qmd
        - text: "Difference-in-Differences"
        - text: "Regression Discontinuity"
        - text: "Selection on Observables"
          href: soo/soo.qmd
        - text: "Regression Models"
        - text: "Latent Variable Models"
          href: latent/latent.qmd

  sidebar:
    - title: "Causal Inference Basics"
      style: floating
      logo: lse2.png
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Homepage"
          href: index.qmd
        - text: "---"
        - text: "Basics of Causality"
          href: frameworks.qmd
        - text: "Issue of Selection Bias"
          href: correlation.qmd
        - text: "Magic of Randomisation"
          href: randomisation.qmd

    - title: "Selection on Observables"
      style: floating
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Selection on Observables"
          href: soo/soo.qmd
        - text: "Choosing an Estimator"
          href: soo/soochoose.qmd
        - text: "---"
        - text: "Linear Regression Estimator"
          href: soo/regress.qmd
        - text: "Fully Interacted Estimator"
          href: soo/interact.qmd
        - text: "Distance Matching"
          href: soo/distance.qmd
        - text: "Propensity Score Matching"
          href: soo/pscore.qmd
        - text: "Genetic Matching"
          href: soo/genetic.qmd
        - text: "Inverse Probability Weighting"
          href: soo/ipw.qmd
        
    - title: "Latent Models"
      style: floating
      border: true
      background: "#f8f9fa"
      foreground: "#36026b"
      contents:
        - text: "Latent Variable Models"
          href: latent/latent.qmd
        - text: "---"
        - text: "Factor Analysis Models"
          href: latent/factor.qmd
        - text: "Reliability and Factor Scores"
          href: latent/scores.qmd
        - text: "Multiple Latent Factors"
          href: latent/multiplefac.qmd
        - text: "Identification and Rotation"
          href: latent/identify.qmd
        - text: "Confirmatory Analysis"
          href: latent/confirmatory.qmd
        - text: "Item Response Theory"
          href: latent/irt.qmd
        - text: "Latent Class Models"
          href: latent/class.qmd
        - text: "---"
        - text: "Structural Equation Models"
        - text: "Longitudinal Models"
        - text: "Clustered Models"
        - text: "---"
        - text: "Principle Components Analysis"
          href: latent/pca.qmd
        - text: "Cluster Analysis"
          href: latent/cluster.qmd
  
format:
  html:
    theme: cosmo
    number-sections: false
    fontsize: 12.5pt
    mainfont: helvetica
    fontcolor: "#3b4b57"
    linkcolor: "#0969da"
    css: styles.css
    toc: true
    toc-depth: 0
    tbl-cap-location: bottom
    reference-location: section
    grid:
      sidebar-width: 270px
      body-width: 720px
      margin-width: 50px
      gutter-width: 1.5em
    html-math-method: mathjax
    crossref:
      eq-prefix: eq.
      def-prefix: definition
      thm-prefix: theorem
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
    include-after-body:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

editor: visual

