---
title: "Basics of Causality"
---

::: small
This page covers how confounders cause pre-existing differences between treated and untreated (selection bias), meaning correlation is not causation.
:::

Let us look at this causal question:

::: center-graph
```{dot}
//| fig-width: 4
//| fig-height: 0.45
digraph example1 {
  bgcolor="transparent";
  // Nodes
  D [shape=box, label="Going to the Hospital (D)"]
  Y [shape=box, label="Health Outcomes (Y)"]

  // Edges
  D -> Y [label="Causal Effect"]

  // Graph styling
  rankdir=LR; // Left to right layout
}
```
:::

We have a group that went to hospital (we will call this group "went"), and a group that "did not go". Using our potential outcomes framework, we can define the treatment effect of the group that went to the hospital:

$$
\tau_\text{went} = \textcolor{green}{{\text{health}}_{\text{went}}^{(1)}} - \textcolor{red}{{\text{health}}_{\text{went}}^{(0)}}
$$

::: small
In red is the counterfactual we do not observe. This is because the individuals who went to the hospital were treated, so we cannot see the world where they are in control.
:::

Now compare the treatment effects above to correlation, which is defined as the difference in observed outcomes:

$$
\begin{align}
\text{correlation} & =  \text{health}_\text{went} - \text{health}_\text{did not go} \\
& = \textcolor{green}{\text{health}_{\text{went}}^{(1)}} - \textcolor{red}{\text{health}_\text{did not go}^{(0)}}
\end{align}
$$

If we compare this correlation to our $\tau_\text{treated}$, we see:

$$
\text{if  } \textcolor{red}{\text{health}_\text{did not go}^{(0)}} ≠ \textcolor{red}{\text{health}_\text{went}^{(0)}}
$$

If this is true (they are different), then correlation is not causation.

::: small
These two quantities are potential outcomes under control, or in another way to think of it, outcomes of the two groups prior to treatment happening.
:::

Thus, if there is a difference between the average health outcomes between those who went to the hospital, and those who did not go to the hospital, **before** treatment is administered, then correlation is not equal to causation. This is because we cannot tell if the difference between the groups is due to treatment, or [due to their pre-existing differences]{.mark}.

<br />

What causes pre-existing differences? Confounders. For example, in our hospital-health example, a confounder could be smoking.

::: small
Smoking is not the only possible confounder, we just use it as an example. Drinking, age, etc. are all other potential confounders.
:::

Smoking will worsen health outcomes. Someone who smokes is also more likely to visit the hospital with health complications. That means people who go to the hospital start out with (on average) worse health outcomes than people who did not go to the hospital.

::: center-graph
```{dot}
//| fig-width: 4
//| fig-height: 1.1
digraph example2 {
  bgcolor="transparent";
  // Nodes
  D [shape=box, pos = "0,0!", label="Going to the Hospital (D)"]
  X [shape=box, pos = "2,0!", label="Smoking (Confounder)"]
  Y [shape=box, pos = "1,-1!", label="Health Outcomes (Y)"]

  // Edges
  {rank=same; D -> Y [label="Causal Effect"]}
  X -> D
  X -> Y [dir=both]
  
  graph [nodesep=0.5, ranksep=0.5]

}
```
:::

::: {.callout-note appearance="simple"}
A confounder is a third variable that has the following characteristics:

1.  The confounder is correlated (positive or negative) with the outcome variable.
2.  The confounder causes who gets and doesn't get the treatment.
3.  The confounder is **not** itself caused by the treatment
:::

::: small
Note requirement 3 - it is a common mistake. Any result of the treatment $D$ cannot be a confounder.
:::

[Confounders cause pre-existing differences]{.mark}, which cause correlation to not equal causation. We must account for confounders to uncover causal effects.

<br />
