---
title: "Basics of Causality"
---

::: small
This page covers the potential outcomes framework and the causal estimands.
:::

In causal inference, we are interested in causal questions:

::: center-graph
```{dot}
//| fig-width: 4
//| fig-height: 0.5
digraph example1 {
  bgcolor="transparent";
  // Nodes
  D [shape=box, label="Treatment (D)"]
  Y [shape=box, label="Outcome (Y)"]

  // Edges
  D -> Y [label="Causal Effect"]

  // Graph styling
  rankdir=LR; // Left to right layout
}
```
:::

::: small
We generally assume the treatment $D$ is binary.
:::

Imagine we have two hypothetical parallel worlds that are copies of each other. Both of these worlds are identical except for one aspect: the treatment:

|                                     |                          |                                 |
|:------------------------------------|:-------------------------|:--------------------------------|
| [Parallel World]{.smallcaps}        | [Treatment]{.smallcaps}  | [Potential Outcome]{.smallcaps} |
| Unit $i$ does not Receive Treatment | $\text{treatment}_i = 0$ | $\T$                            |
| Unit $i$ Receives Treatment         | $\text{treatment}_i = 1$ | $\C$                            |

: {tbl-colwidths="\[45,30,25\]" .bordered}

<br />

The only difference between the two worlds is the treatment. Thus, any difference in outcomes between the two worlds must be the [causal effect]{.mark} of the treatment.

$$
\tau_i = \T - \C
$$

::: small
Technically, we need another assumption, SUTVA, for this to be true. I will explain this assumption as part of the identification assumptions.
:::

However, in reality, we do not have two parallel worlds. Thus, by definition, one of the potential outcomes is not observed in our real world - the [counterfactual]{.mark}.

|                                 |                                |                              |
|:--------------------------------|:-------------------------------|:-----------------------------|
| [In the Real World]{.smallcaps} | [Observed Outcome]{.smallcaps} | [Counterfactual]{.smallcaps} |
| $i$ receives treatment          | $\Y= \T$                       | $\Cred$                      |
| $i$ did not receive treatment   | $\Y = \C$                      | $\Tred$                      |

: {tbl-colwidths="\[33,40,27\]" .bordered}

::: small
I will denote potential outcomes in purple, and counterfactual potential outcomes in red.
:::

<br />

The [fundamental problem of causal inference]{.mark} is that in order to calculate our individual treatment effect $\tau$, we need both potential outcomes. Our goal is to estimate causal effects without observing counterfactuals. This is difficult at the individual level, so instead, we focus on average treatment effects for groups:

|                                               |                        |                                                                                               |
|:----------------------------------------------|:-----------------------|:----------------------------------------------------------------------------------------------|
| [Group Effects]{.smallcaps}                   | [Notation]{.smallcaps} | [Definition]{.smallcaps}                                                                      |
| Average Treatment Effect (ATE)                | $\tau_\text{ATE}$      | The average treatment effects for all individuals in our study (treated and untreated).       |
| Average Treatment Effect on the Treated (ATT) | $\tau_\text{ATT}$      | The average treatment effect but only for individuals who receive the treatment in our study. |
| Local Average Treatment Effect (LATE)         | $\tau_\text{LATE}$     | The average treatment effect but only for a specific (local) group of individuals in a study. |

: {tbl-colwidths="\[30, 15, 55\]" .bordered}

<br />
