---
title: "Resources on Causal Inference and Social Science Statistics"
subtitle: "Methodology for Political Science and Political Economy (PSPE)"
---

For my personal website, see <http://kevinli03.github.io>

This repository contains resources on causal inference and social statistics methods, and implementing these methods in R.

-   **Difference-in-Differences**, including modern advancements from 2021-2025.

-   Other **causal estimators**, such as instrumental variables, regression discontinuity, and more.

-   **Latent variable models**, such as factor analysis, item response theory, and structural equation modelling.

-   **Regression Models** (not too much in detail, mostly implementation and interpretation).

::: small
This repository isn't meant to teach you these methods (although I do include explanations of these methods). It is primary aimed as a reference when implementing methods. Check out the [additional resources](resources.qmd) for more teaching material.
:::

Use the top navigation bar to navigate between different methods. Use the side navigation bar to navigate within a method.
