---
title: "Latent Variable Models"
---

A latent variable model connects a unobserved variable (**latent factor** $\xi$) with a few observed variables (**items** $X_1, X_2, \dots$) that are considered imperfect measures of the latent factor.

::: center-graph
```{dot}
//| fig-width: 4.5
//| fig-height: 1.4
digraph example2 {
  bgcolor="transparent";
  // Nodes
  F [shape=box, pos = "0,0!", label=<<FONT FACE="Helvetica">&xi; (Unobserved)</FONT>>]
  X1 [shape=box, pos = "2,0!", label="X1 (Observed)"]
  X2 [shape=box, pos = "1,-2!", label="X2 (Observed)"]
  X3 [shape=box, pos="1,0!", label="X3 (Observed)"]

  // Edges
  {F -> X1 [label=<<FONT FACE="Helvetica">&lambda;</FONT>>]}
  {F -> X2 [label=<<FONT FACE="Helvetica">&lambda;</FONT>>]}
  {F -> X3 [label=<<FONT FACE="Helvetica">&lambda;</FONT>>]}
  
  graph [nodesep=0.5, ranksep=0.5]

}
```
:::

::: small
For example, maybe we want to measure the political ideology of a senator. We cannot directly observe the political ideology (the latent factor), but we can observe how they vote on different bills (the items)
:::

Latent variable models assume we can model the relationship between each observed item and the latent factor with some sort of regression model. The coefficient of each regression (often denoted $\lambda$) is the relationship between each item and the factor.

::: small
For example, in the figure above, each item (X1, X2, X3) is related to the factor (F) with by a $\lambda$ coefficient.
:::

These $\lambda$ are called **factor loadings**. We can interpret the estimated factor loadings $\widehat\lambda$ to interpret what the unobserved factor actually is measuring.

::: small
For example, if a factor has a strong relationship with one item, and a weaker relationship with another item, we might conclude that the factor measures the first item more than the second item.
:::

We can also use latent variable models to create **factor scores** $\widehat\xi$, which are basically actual values of the latent variable for each individual $i$ in our data. This allows us to use the latent variable in other statistical models.

The choice of latent variable model depends on the type of items/factors:

|                                      |                           |                         |
|-----------------------|-------------------------|-----------------------|
| [Model]{.smallcaps}                  | [Factor Type]{.smallcaps} | [Item Type]{.smallcaps} |
| [Factor Analysis](factor.qmd)        | Continuous                | Continuous              |
| [Item Response Theory](irt.qmd)      | Continous                 | Categorical/Binary      |
| [Structural Class Models](class.qmd) | Categorical/Binary        | Categorical/Binary      |

: {tbl-colwidths="\[36,32,32\]" .bordered}

<br />

All models allow for multiple factors $\xi_1, \xi_2, \dots$ as well. If we have many items, some items might only measure on factor, others both factors.

Each latent model also has the ability to conduct **confirmatory analysis**. This is basically when we, based on theoretical reasons (such as reading the literature), impose certain restrictions on models, and test if this hypothesised model is good.

::: small
This typically takes the form of setting certain factor loadings $\lambda$ to 0, meaning a certain item does not measure one of the factors.
:::

We can also combine different structural models together to form **structural equation models** (see the structural equation models part).
