---
title: "Stagged Difference-in-Differences"
---

::: small
Ensure you understand the classical difference-in-differences design before starting this.
:::

In the classical difference-in-differences design, all units in the treatment group receive treatment at the same time. However, in reality, this is not that common. It is very common that some units receive treatment before others.

::: small
For example, in the US, states often adopt different policies at different times - such as the staggered adoption of mail-in voting, or the staggered adoption of the common core curriculum.
:::

The **staggered difference-in-differences** design is an extension on the classical design, which allows for staggered implementation of treatment.

Essentially, this design is a combination of a bunch of smaller classical difference-in-differences designs.

-   For example, consider that we have 4 groups. Group 1 receives the treatment in period 1, group 2 receives the treatment in period 2, and group 3 receives the treatment in period 3. Group 4 never receives the treatment.
-   In this scenario, we essentially have 3 smaller classical difference-in-differences combined into one larger study: one for group 1, one for group 2, and one for group 3.

Just like in the classical design, the staggered design can acommodate panel data (more common) or repeated cross-sections. Unlike the classical design however, there are far more estimators to choose from.

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Two-Way Fixed Effects Estimator](twfe.qmd)                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                           |
| The TWFE estimator is possible in staggered DiD just like in the classical design - and is quite simple. However, there are a variety of issues outlined [here](twfestaggered.qmd), that make it more dubious.                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Gardner (2021) 2-Stage DiD](did2s.qmd)                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                           |
| This estimator accounts for the issues with TWFE by estimating the missing counterfactuals to find the treatment effect.                                                                                                                                                                                  |
|                                                                                                                                                                                                                                                                                                           |
| ::: small                                                                                                                                                                                                                                                                                                 |
| Kevin's Notes: very simple and intuitive, however, not very flexible or robust. If you are interested in a better counterfactual estimator, use Liu et al (2024).                                                                                                                                         |
| :::                                                                                                                                                                                                                                                                                                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Wooldridge (2021) Extended Two-Way Fixed Effects](etwfe.qmd)                                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                           |
| This estimator accounts for the issues with TWFE by adding interaction terms to model heterogeneity.                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                           |
| ::: small                                                                                                                                                                                                                                                                                                 |
| Kevin's Notes: Can handle non-linear models like poisson and logistic. Very similar to Sun and Abraham. It handles conditional parallel trends more flexibly than Sun and Abraham. However, it cannot estimate pre-treatment dynamic effects, so if you need to test parallel trends use Sun and Abraham. |
| :::                                                                                                                                                                                                                                                                                                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Sun and Abraham (2021)](sunab.qmd)                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                           |
| This estimator accounts for the issues with TWFE by adding interaction terms to model heterogeneity.                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                           |
| ::: small                                                                                                                                                                                                                                                                                                 |
| Kevin's Notes: Very similar to Wooldridge. It can estimate pre-treatment dynamic treatment effects when Wooldridge cannot. However, it is less flexible and robust when dealing with conditional parallel trends.                                                                                         |
| :::                                                                                                                                                                                                                                                                                                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Callaway and Sant'Anna (2021)](cs.qmd)                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                           |
| This estimator accounts for the issues with TWFE through matching and reweighting.                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                           |
| ::: small                                                                                                                                                                                                                                                                                                 |
| Kevin's Notes: Probably the most well regarded in econometrics. Intuitively, it might be the simplest, however, technically, it is very complex. It is semi-parametric, making it more flexible than regression based methods.                                                                            |
| :::                                                                                                                                                                                                                                                                                                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Liu et al (2022) Counterfactual                                                                                                                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                                           |
| This estimator accounts for the issues with TWFE by estimating the missing counterfactuals to find the treatment effect.                                                                                                                                                                                  |
|                                                                                                                                                                                                                                                                                                           |
| ::: small                                                                                                                                                                                                                                                                                                 |
| Kevin's Notes: This is a more complex estimator that (debatedly) might not even be a difference-in-differences estimator, as it draws a lot from synthetic controls. It is quite flexible and preferable to Gardner (2021), but is more complex and hard to explain.                                      |
| :::                                                                                                                                                                                                                                                                                                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered}
