---
title: "Choosing an Estimator"
---

We know how selection on observables works now. But how do we actually implement selection on observables? Below are a list of estimators and their strengths/weaknesses. You can use multiple simultaneously for robustness.

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Linear Regression Estimator](regress.qmd)                                                                                                                                                                                        |
|                                                                                                                                                                                                                                   |
| -   Estimand: ATE                                                                                                                                                                                                                 |
| -   Pros: very simple, works well with small datasets.                                                                                                                                                                            |
| -   Cons: 1) requires linear relationship between confounders and outcome, 2) does not work when there are heterogenous treatment effects.                                                                                        |
|                                                                                                                                                                                                                                   |
| ::: small                                                                                                                                                                                                                         |
| Kevin's Comments: since heterogeneity is so common in almost everything, I would recommend against using this estimator unless nothing else is possible. The fully interacted estimator (below) is just a better version of this. |
| :::                                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Fully Interacted Estimator](interact.qmd)                                                                                                                                                                                        |
|                                                                                                                                                                                                                                   |
| -   Estimand: ATE                                                                                                                                                                                                                 |
| -   Pros: 1) modified regression to allow for heterogenous effects, 2) still relatively simple.                                                                                                                                   |
| -   Cons: requires linear relationship between confounders and outcome                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Distance Matching](distance.qmd)                                                                                                                                                                                                 |
|                                                                                                                                                                                                                                   |
| -   Estimand: ATT                                                                                                                                                                                                                 |
| -   Pros: 1) non-parametric, so no need to assume the type of relationship between confounders and outcome. 2) relatively intuitive idea.                                                                                         |
| -   Cons: 1) can be badly biased when more than 3-5 confounders, 2) throws out unmatched data so wastes data.                                                                                                                     |
|                                                                                                                                                                                                                                   |
| ::: small                                                                                                                                                                                                                         |
| Kevin's Comments: there is little reason to use distance matching over genetic matching, unless your machine physically cannot estimate genetic matching.                                                                         |
| :::                                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Propensity Score Matching](pscore.qmd)                                                                                                                                                                                           |
|                                                                                                                                                                                                                                   |
| -   Estimand: ATT                                                                                                                                                                                                                 |
| -   Pros: 1) non-parametric, so no need to assume the type of relationship between confounders and outcome, 2) can handle larger amounts of confounders than distance matching.                                                   |
| -   Cons: 1) needs a large sample size to not be biased, 2) throws out unmatched data so wastes data.                                                                                                                             |
|                                                                                                                                                                                                                                   |
| ::: small                                                                                                                                                                                                                         |
| Kevin's Comments: there is little reason to use propensity score matching over genetic matching, unless your machine physically cannot estimate genetic matching.                                                                 |
| :::                                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Genetic Matching](genetic.qmd)                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
| -   Estimand: ATT                                                                                                                                                                                                                 |
| -   Pros: 1) non-parametric, so no need to assume the type of relationship between confounders and outcome, 2) shown to be the best matching estimator                                                                            |
| -   Cons: 1) throws out unmatched data so wastes data, 2) can be computationally taxing.                                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Inverse Probability Weighting](ipw.qmd)                                                                                                                                                                                          |
|                                                                                                                                                                                                                                   |
| -   Estimand: ATE                                                                                                                                                                                                                 |
| -   Pros: 1) non-parametric, so no need to assume the type of relationship between confounders and outcome, 2) does not waste data like matching methods do.                                                                      |
| -   Cons: requires a large sample size to be unbiased.                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[100\]" .bordered}

<br />
